### ISSUE TITLE
Fataler Fehler in WP 6.0.0

### ISSUE THREAD

**Issue by Mottek57** [wernerjoss/wp-caldav2ics#5]
Ahoi allerseits,

Sorry, aber das Plugin wirf bei der Installation einen fatalen Fehler…

“Das Plugin kann nicht aktiviert werden, da es einen fatalen Fehler erzeugt.”

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /homepages/23/KundNr/htdocs/wordpress/wp-content/plugins/wp-caldav2ics/Caldav2ics_Plugin.php:70 Stack trace: #0 /homepages/23/KundNr/htdocs/wordpress/wp-content/plugins/wp-caldav2ics/Caldav2ics_LifeCycle.php(29): Caldav2ics_Plugin->initOptions() #1 /homepages/23/KundNr/htdocs/wordpress/wp-content/plugins/wp-caldav2ics/caldav2ics_init.php(34): Caldav2ics_LifeCycle->install() #2 /homepages/23/KundNr/htdocs/wordpress/wp-content/plugins/wp-caldav2ics/wp-caldav2ics.php(70): Caldav2ics_init('/homepages/23/d...') #3 /homepages/23/KundNr/htdocs/wordpress/wp-admin/includes/plugin.php(2313): include_once('/homepages/23/d...') #4 /homepages/23/KundNr/htdocs/wordpress/wp-admin/plugins.php(192): plugin_sandbox_scrape('wp-caldav2ics/w...') #5 {main} thrown in /homepages/23/KundNr/htdocs/wordpress/wp-content/plugins/wp-caldav2ics/Caldav2ics_Plugin.php on line 70

KundNr war meine Kundennummer und die will ja hier keiner wissen… 😉

Besteht die Chance, daß der Fehler noch gefixt wird oder ist das tolle Plugin jetzt verloren?

Mit freundlichen Grüßen

Volker

**Comment by wernerjoss** [comment]
Hi Volker,
kann es sein dass auf deinem Server PHP 8.0 (oder höher) installiert ist ?
das könnte ein Grund für den Fehler sein.
In meinem docker container mit WP 6.0/PHP 7.4 läuft das Plugin ohne Probleme.
Gruss
Werner

**Comment by Mottek57** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Hallo Werner,Entschuldige die späte Antwort...Joh... bei mir läuft meist schon PHP 8.1...Ich habe da zu wenig Ahnung davon......jeder sagt, daß die 8er Version performanter sei und man aufrüsten sollte...Arrggghhhh!!!! Warum können die nicht abwärts kompatibel bleiben...Kannst du das mit der 8.0/8.1 fixen?
Beste Grüße
Volker
 
 

Werner Joss schrieb am 23.06.2022 17:12 (GMT +02:00):

Hi Volker,kann es sein dass auf deinem Server PHP 8.0 (oder höher) installiert ist ?das könnte ein Grund für den Fehler sein.In meinem docker container mit WP 6.0/PHP 7.4 läuft das Plugin ohne Probleme.GrussWerner

**Comment by wernerjoss** [comment]
Hi Volker,
nein, ich kann (bzw. will) das momentan nicht fixen: ich habe Wordpress nur noch in einer docker Instanz, für die ich das offizielle WP docker image verwende, und das ist noch auf PHP 7.4.
und das wird wohl auch noch so lange so sein, bis WP voll kompatibel ist zu PHP 8.0/8.1.
Gruss
Werner

**Comment by wernerjoss** [comment]
issue closed as not reproducible even with PHP 8.0/8.1 test.
so it has nothing to do with this.

**Comment by wernerjoss** [comment]
I'm now re-opening this issue, as I could reproduce the Problem with a WP 6.1.1 / PHP 8.1 docker instance.
the fix is now online, please test if this works for you.

**Comment by wernerjoss** [comment]
fix is now in release 1.3.0, closing this issue now.
