### ISSUE TITLE
Version 1.3.3 breaks unfolding in Description

### ISSUE THREAD

**Issue by Bavarianspirit** [wernerjoss/wp-caldav2ics#7]
The exported ICS File directly shows like this:

DESCRIPTION:An diesem Tag wurde die Internetseite:\nhttps://website
 .de\nzum ersten mal Online geschalten

![grafik](https://github.com/wernerjoss/wp-caldav2ics/assets/35309163/3bbe1612-e411-447e-a369-9a3b4aaa46d4)

If wp-caldav2ics imports this ics file into the website storage, the imported ics file shows like this:

DESCRIPTION:An diesem Tag wurde die Internetseite:\nhttps://website.de

 \nzum ersten mal Online geschalten

![grafik](https://github.com/wernerjoss/wp-caldav2ics/assets/35309163/5b264d24-347d-48ab-91c1-099a3222eac8)

it looks like that wp-caldav2ics does a reformating of the ics file.
but this breaks the unfolding because folding of Description should be a "line break" + "space" or "tab"
after the reformating we have two "line break" + "space"

look here:
https://www.rfc-editor.org/rfc/rfc5545#section-3.1

is it possible to import the ics file into the website without reformating?

**Comment by wernerjoss** [comment]
sorry I missed this so long :disappointed:  - another user reported this in the [WP Repo](https://wordpress.org/support/topic/converted-openxchange-calendar-subscibe-to-google-didnt-work/).
fixed now in v1.3.4
